// 生成 spec/capacity-cases.json：网页版容量模型（sim.js）的输入和期望输出，Unity 版的 C# 移植用同一份用例核对。
// 容量模型或目录数值有意变更后运行：npm run capacity-cases
import {writeFileSync} from 'node:fs';
import {buildLayout} from '../src/layout-export.js';
import {compute} from '../src/sim.js';
import {CAT, CATALOG} from '../src/catalog.js';
import {GRID} from '../src/grid.js';
import {PRESETS} from '../src/layout.js';
import {getLang, setLang} from '../src/i18n.js';

export const CASES_PATH = new URL('../../spec/capacity-cases.json', import.meta.url);
const META = {date: '2026-09-17'};

// 用例里的问题文本固定用中文：Unity 的 C# 容量模型输出中文并逐字比对
export function buildCases(){
  const previous = getLang();
  setLang('zh');
  try { return cases(); } finally { setLang(previous); }
}

function cases(){
  const inputs = [
    ...Object.entries(PRESETS).map(([name, p]) => [`preset ${name}`, p.u, p.list]),
    ['every type once', 10, CATALOG.map((t, i) => [t.id, i, 9])],
    ['single gb200 without facilities', 2, [['gb200', 0, 0]]],
    ['four kyber over utility', 2, [0, 1, 2, 3].map(x => ['kyber', x, 0])],
    ['dgx air cooled', 2, [['dgx', 0, 0], ['crah', 1, 0], ['rpp', 2, 0], ['ib', 3, 0]]],
  ];
  return inputs.map(([name, u, list]) => {
    const items = list.map(([type, x, z]) => ({type, x, z}));
    const s = compute(items, CAT, u);
    return {
      name,
      layout: buildLayout(items, CAT, u, GRID, META),
      expected: {
        itKw: s.it, gpus: s.gpus, liquidHeatKw: s.liqHeat, airHeatKw: s.airHeat,
        liquidCapacityKw: s.liqCap, airCapacityKw: s.airCap, distributionKw: s.dist, fabricPorts: s.ports,
        overheadKw: s.ovh, capexMusd: s.capex, facilityKw: s.facility, pue: s.pue, blocking: s.blocking,
        issues: s.issues.map(i => ({level: i.lvl, text: i.txt})),
      },
    };
  });
}

if (import.meta.url === `file://${process.argv[1]}`){
  writeFileSync(CASES_PATH, JSON.stringify({description: 'Generated by web/scripts/capacity-cases.js from web/src/sim.js. Do not edit by hand.', cases: buildCases()}, null, 2) + '\n');
  console.log('spec/capacity-cases.json written');
}
