// Generates spec/capacity-cases.json: inputs and expected outputs of the web capacity model (sim.ts); the Unity C# port checks against the same cases.
// Run after intentional changes to the capacity model or catalog values: npm run capacity-cases
import {writeFileSync} from 'node:fs';
import {buildLayout} from '../src/layout-export.ts';
import {compute, MODEL_VERSION} from '../src/sim.ts';
import {CAT, CATALOG, CATALOG_VERSION} from '../src/catalog.ts';
import {GRID} from '../src/grid.ts';
import {PRESETS} from '../src/layout.ts';
import {toItems} from '../src/edit.ts';
import type {Entry} from '../src/types.ts';
import {getLang, setLang} from '../src/i18n.ts';

export const CASES_PATH = new URL('../../spec/capacity-cases.json', import.meta.url);
const META = {date: '2026-09-17'};

// Issue text in the cases is always Chinese: the Unity C# capacity model outputs Chinese and is compared verbatim
export function buildCases(): ReturnType<typeof cases>{
  const previous = getLang();
  setLang('zh');
  try { return cases(); } finally { setLang(previous); }
}

function cases(){
  const inputs: [name: string, u: number, list: Entry[]][] = [
    ...Object.entries(PRESETS).map(([name, p]): [string, number, Entry[]] => [`preset ${name}`, p.u, p.list]),
    ['every type once', 10, CATALOG.map((t, i): Entry => [t.id, i, 9])],
    ['single gb200 without facilities', 2, [['gb200', 0, 0]]],
    ['four kyber over utility', 2, [0, 1, 2, 3].map((x): Entry => ['kyber', x, 0])],
    ['dgx air cooled', 2, [['dgx', 0, 0], ['crah', 1, 0], ['rpp', 2, 0], ['ib', 3, 0]]],
  ];
  return inputs.map(([name, u, list]) => {
    const items = toItems(list);
    const s = compute(items, CAT, u);
    return {
      name,
      layout: buildLayout(items, CAT, u, GRID, META),
      expected: {
        itKw: s.it, gpus: s.gpus, liquidHeatKw: s.liqHeat, airHeatKw: s.airHeat,
        liquidCapacityKw: s.liqCap, airCapacityKw: s.airCap, distributionKw: s.dist, fabricPorts: s.ports,
        overheadKw: s.ovh, capexMusd: s.capex, facilityKw: s.facility, pue: s.pue, blocking: s.blocking,
        issues: s.issues.map(i => ({level: i.lvl, text: i.txt})),
      },
    };
  });
}

if (import.meta.url === `file://${process.argv[1]}`){
  writeFileSync(CASES_PATH, JSON.stringify({description: 'Generated by web/scripts/capacity-cases.ts from web/src/sim.ts. Do not edit by hand.', catalogVersion: CATALOG_VERSION, modelVersion: MODEL_VERSION, cases: buildCases()}, null, 2) + '\n');
  console.log('spec/capacity-cases.json written');
}
