// Generates docs/examples.md: one share link and one line of numbers per example hall in src/examples.ts.
// Run after changing the examples, the catalog or the capacity model: npm run examples
// Output is deterministic (fixed order, no timestamps), so re-running only changes the file when the halls do.
import {writeFileSync} from 'node:fs';
import {examples, check, type Example} from '../src/examples.ts';
import {encodeLayout} from '../src/share-link.ts';
import {compute, fmt} from '../src/sim.ts';
import {toItems} from '../src/edit.ts';
import {CAT} from '../src/catalog.ts';
import {GRID} from '../src/grid.ts';

export const DOC_PATH = new URL('../../docs/examples.md', import.meta.url);
const SITE = 'https://datahall-eight.vercel.app/';

// encodeLayout returns the hash content without the leading '#'
const linkFor = (ex: Example): string => `${SITE}#${encodeLayout(ex.layout)}`;

// One line of facts: what the hall holds, what it costs in power, and whether it passes
function factsFor(ex: Example): string{
  const items = toItems(ex.layout.list);
  const s = compute(items, CAT, ex.layout.u);
  const claims = check(ex, CAT);
  const racks = items.filter(i => CAT[i.type].gpus).length, support = items.length - racks;
  const phases = claims.phases ?? 1;
  const facts = [
    claims.powers ? 'Powers on' : 'Cannot power on',
    `${s.gpus} GPUs`,
    `${fmt(s.it)} IT load`,
    `PUE ${s.pue.toFixed(2)}`,
    `${racks} GPU ${racks === 1 ? 'rack' : 'racks'} and ${support ? `${support} support ${support === 1 ? 'unit' : 'units'}` : 'no support units'}`,
    `${ex.layout.u} MW feed`,
    `${phases} ${phases === 1 ? 'phase' : 'phases'}`,
  ];
  if (claims.powers) facts.push(claims.n1 ? 'N+1' : 'not N+1');
  return facts.join(' · ');
}

export function buildDoc(): string{
  const entries = examples(CAT, GRID).map(ex => [
    `## ${ex.title}`,
    ex.blurb,
    `[Open this hall](${linkFor(ex)})`,
    factsFor(ex),
  ].join('\n\n'));
  return [
    '<!-- Generated by `npm run examples` (web/scripts/examples-doc.ts). Do not edit by hand. -->',
    '# Example halls',
    'Each link below opens the [live demo](' + SITE + ') with a ready-made hall: the layout travels in the URL hash, so nothing is sent to a server and every hall can be edited, exported or broken on purpose once it is open. The halls are built from the app\'s own presets and goal generator, and the numbers come from the same capacity model the page uses.',
    'The app is in English by default. Put `?lang=zh` before the `#` to open a hall with the Simplified Chinese interface.',
    ...entries,
  ].join('\n\n') + '\n';
}

if (import.meta.url === `file://${process.argv[1]}`){
  writeFileSync(DOC_PATH, buildDoc());
  console.log(`docs/examples.md written: ${examples(CAT, GRID).length} examples`);
}
